config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
get 'tasks', to: 'tasks#index', as: :tasks
post 'tasks', to: 'tasks#create'
get'/tasks/new', to: 'tasks#new'
get'/tasks/:id/edit', to: 'tasks#edit', as: :edit
get'/tasks/:id', to: 'tasks#show', as: :task
patch '/tasks/:id', to: 'tasks#update'
delete '/tasks/:id', to: 'tasks#destroy'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  def index
    @tasks_list = Task.all
  end

  def show
    @task = Task.find(params[:id])
  end

  def new
    @task = Task.new
  end

  def create
    task = Task.new(task_params)
    task.save
    redirect_to task_path(task)
  end

  def edit
    @task = Task.find(params[:id])
  end

  def update
    task = Task.find(params[:id])
    task.update(task_params)
    redirect_to task_path(task)
  end

  def destroy
    task = Task.find(params[:id])
    task.destroy
    redirect_to tasks_path
  end

  private

  def task_params
    params.require(:task).permit(:title, :details, :completed)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/task_helper.rb
module TaskHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/_form.html.erb
<%= form_for(task) do |f| %>
  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :details %>
    <%= f.text_field :details, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label "Done" %>
    <%= f.check_box :completed %>
  </div>
  <%= f.submit class: 'btn btn-primary' %>
<% end %>

app/views/tasks/edit.html.erb
<h1>Edit Task</h1>
<%= render 'form', task: @task %>

app/views/tasks/index.html.erb
<h1><i class="fas fa-tasks"></i> My Tasks </h1>
<ul>
<% @tasks_list.each do |task| %>
<% if task.completed == true %>
  <li>
  <i class="far fa-check-square"></i>
  <%= link_to task_path(task) do %>
  <%= task.title.capitalize %></li>
  <% end %>
<% elsif task.title.length >= 1 %>
  <li>
  <i class="far fa-square"></i>
  <%= link_to task_path(task) do %>
  <%= task.title.capitalize %></li>
<% end %>
<% end %>
<% end %>
</ul>
<h3><i class="fas fa-plus"></i> <%= link_to "Create Task", tasks_new_path %></h3>

app/views/tasks/new.html.erb
<h1>Create Task</h1>
<%= render 'form', task: @task %>

app/views/tasks/show.html.erb
<h1> <%= @task.title %></h1>
<% if @task.title.length <= 1 %>
  <h1> Your must give your task a name.
    <%= link_to new_task_path do %>
      <i class="fas fa-pencil-alt"></i>
    <% end %>
  </h1>
<% else %>
  <h3 class="task-details"><%= @task.details %></h3>
<% if @task.completed == true %>
  <h4><i class="far fa-check-square"></i> The task is completed</h4>
<% else %>
  <h4><i class="far fa-square"></i> You need to complete this task </h4>
<% end %>
<h3><%= link_to "Update task", edit_path %></h3>
<h3><%= link_to "Delete task", task_path(@task),
      method: :delete,
      data: { confirm: "Are you sure?" } %>
</h3>
<% end %>
<h3><%= link_to "Back to lists", tasks_path %></h3>